version: "2.18.1"
services:
  mysqldb:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: task_management_system
    ports:
      - "3306:3306"
    volumes:
      - task_management_system_db_data:/var/lib/tms
    networks:
      - tms

  tms:
    container_name: tms
    restart: always
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/task_management_system
    networks:
      - tms
volumes:
  task_management_system_db_data:
networks:
  tms: